### PR TITLE
Highlight almost all missing syntax.

### PR DESCRIPTION
**Pull request by pema99**
Hey, I've been working more on syntax highlighting for F# in my spare time, and thought I might as well submit another PR. I know I just told you to push for review and eventual merge, but I don't believe anyone has done a review yet. Either way, do what you see fit, I would just like what is basically the only implementation of F# syntax highlighting for Kakoune to be unified in one place, and of course I would still love this to be reviewed and merged as soon as possible. The reason I am submitting another PR to this repo is, that I finished these changes faster than I anticipated.

I added highlighting for basically all the things that were missing.
Changelog:
- Highlight comments with the comment color instead of string.
- Highlight computation expression keywords.
- Highlight prefixes ´!´ for reference cells and ´#´ for flexible types.
- Highlight all the nullable operators.
- Highlight all cases of ´~´ (operator overloading, prefix and bitwise not).
- Highlight all valid character, integer and floating point literals.
- Highlight verbatim strings and ascii strings.

[Link to original PR for referencing.](https://github.com/mawww/kakoune/pull/3145)

### CODE REVIEW

**Comment by nhey** [comment]
a

Cool! Is it possible to fix this?

**Comment by pema99** [comment]
I fixed it. Unless I am mistaken this was an issue before I touched the file. Either way, I'll make a test document and test all operators that should be highlighted.

**Comment by pema99** [comment]
As of this latest I have tested every official symbol/operator listed on MSDN. Here is a list of every syntax which is not highlighted:
```
{ }
_
[| |]
;
:
[ ]
.
,
( )
(| |)
'
``stuff``
```
I personally do not believe these should be highlighted (maybe with the exception of `:`), but I would like to hear what you think. Other than these, all the operators seem to be highlighted as intended now.

**Comment by nhey** [comment]
Seems like a sane choice not to include these. Thanks again for your work

**Pull request merged**
