### PR TITLE
Fixed missing operators and multiline comments

### PR DESCRIPTION
**Pull request by pema99**
Hey, I fixed some the issue's I mentioned in [this PR.](https://github.com/mawww/kakoune/pull/3145)

Changes made:
- Fix the edge case where `(*)` was being matched as the beginning of a multiline comment
- Highlight `nameof` from F# 4.7
- Highlight all the missing tuple piping operators
- Highlight quotations
- Highlight the type coercion operators
- Highlight the ref cell operator `:=`

### CODE REVIEW

**Comment by pema99** [comment]
Some further considerations:
I didn't highlight `!` which is used for reference cells as it conflicts with keywords such as `yield!`, highlighting in 2 different colors. Not quite sure how to solve this.
The computation expression keywords with `!` appended should probably be hightlighted as keywords?
Also all, the nullable operators are still lacking highlighting.

**Comment by nhey** [comment]
Thanks!

> Additionally, might I suggest adding highlighting for all literals (chars, numbers, etc.), and not just strings? I would be willing to attempt this.

Sure. I did not implement this because I prefer a dull colorscheme -- but this should be set in the colorscheme and not the syntax file. Would you like me to remove the [WIP] from my PR in the kakoune repo and push for a merge, s.t. you can pull request further changes directly to the kakoune repo?

**Comment by pema99** [comment]
Hey, I'm not quite sure I follow. Shouldn't highlighters be added to all literals like they are for [example in c-family.kak](https://github.com/nhey/kakoune/blob/fsharp-filetype/rc/filetype/c-family.kak#L284)? Please correct me if I am wrong. About the removal of the [WIP] tag and pushing for a merge, that would definitely be appreciated. I would like to see this in upstream asap as I use F# for school work. I will look into adding highlighting for nullable operators and computation expression keywords soon.

**Comment by nhey** [comment]
> Shouldn't highlighters be added to all literals like they are for [example in c-family.kak](https://github.com/nhey/kakoune/blob/fsharp-filetype/rc/filetype/c-family.kak#L284)?

Yes, they should be added.

I will remove the WIP-tag. Generally, I don't have a strong opinion about what is added to this syntax file -- it's really up to anyone who would like to contribute.
Like you, I used F# for coursework so I made the syntax file back then. I don't however use F# these days, so I probably won't be contributing much after this; Nonetheless, I really commend your efforts into making this a more complete syntax highlighting!

**Pull request merged**
